### ISSUE TITLE
array_patten输出E没有合成，是阵元相位，和给出的例子用法不一致

### ISSUE THREAD

**Issue by jackxu8** [qwe14789cn/radar_tools#2]
array_patten
中最后输出的E是阵列中每个阵元或者子阵的相位，按照例子中的用法，输出E应该是整个阵列合成后的相位，所以这个文件的最后应该有一行E = sum(E,2);

**Comment by qwe14789cn** [comment]
已经修改说明文件
当初是为了方便，就把所有阵列放出来，所以没有修改描述部分
